/**
 * Generate .play/manifest.ts — the single source of truth the player imports.
 *
 * GENERATED, never hand-edited: `start` is the cumulative sum of measured
 * durations, so the beats butt-joint into one continuous track and the "no
 * dead frames" rule holds by construction rather than by discipline.
 *
 * Interactive time is deliberately NOT in the timeline. A popup pauses the
 * clock while it is open, so `start` stays a pure function of the narration
 * and never has to account for how long a learner spent playing.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { loadConfig, paths } from "../config.mjs";
import { head, info, ok, clock } from "../log.mjs";

const j = (v) => JSON.stringify(v);

export const run = async () => {
  const cfg = await loadConfig();
  const p = paths(cfg);

  let timings;
  try {
    timings = JSON.parse(await readFile(p.timings, "utf8"));
  } catch {
    throw new Error(`no timings.json — run \`play-lesson timings\` first`);
  }

  const missing = cfg.beats.filter((b) => typeof timings[b.id] !== "number");
  if (missing.length) {
    throw new Error(
      `timings.json is missing ${missing.length} beat(s): ${missing.map((b) => b.id).join(", ")}\n` +
      `  It is stale — re-run \`play-lesson timings\`.`,
    );
  }

  let at = 0;
  const beats = cfg.beats.map((b) => {
    const row = { id: b.id, chapter: b.chapter, start: Math.round(at * 1000) / 1000, dur: timings[b.id], interactive: b.interactive };
    at += timings[b.id];
    return row;
  });
  const runtime = Math.round(at * 1000) / 1000;

  const src = `/**
 * GENERATED by play-lesson — do not edit.
 * Source: lesson.config.json + timings.json. Re-run \`play-lesson manifest\`.
 *
 * \`start\` is the cumulative narration offset with NO gaps: the beats are
 * butt-jointed, so the audio plays as one continuous track.
 */

export type Interactive = { kind: string; title: string; hint: string };
export type Beat = {
  id: string;
  chapter: number;
  /** seconds from the start of the lesson */
  start: number;
  dur: number;
  interactive: Interactive | null;
};

export const SLUG = ${j(cfg.slug)};
export const TITLE = ${j(cfg.title)};
export const HANDS_ON_LABEL = ${j(cfg.handsOnLabel)};

export const CHAPTERS: { short: string; full: string }[] = ${JSON.stringify(cfg.chapters, null, 2)};

export const BEATS: Beat[] = ${JSON.stringify(beats, null, 2)};

/** Total narration, seconds. Interactive time is learner-paced and not counted. */
export const RUNTIME_SEC = ${runtime};

export const beatAt = (sec: number): Beat =>
  BEATS.find((b) => sec < b.start + b.dur) ?? BEATS[BEATS.length - 1];
`;

  await mkdir(p.generated, { recursive: true });
  await writeFile(p.manifest, src, "utf8");

  head(`manifest · ${cfg.slug}`);
  const hands = beats.filter((b) => b.interactive);
  ok(`.play/manifest.ts · ${beats.length} beats · ${cfg.chapters.length} chapters · ${clock(runtime)}`);
  info(`${hands.length} interactive${hands.length === 1 ? "" : "s"}${hands.length ? `: ${hands.map((b) => b.interactive.kind).join(", ")}` : ""}`);
  return { beats, runtime };
};
